// Autogenerated from Pigeon (v28.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


class EngineInfo {
  EngineInfo({
    required this.engineVersion,
    required this.abiVersion,
    required this.apiVersion,
    required this.phase,
    required this.buildId,
  });

  String engineVersion;

  int abiVersion;

  int apiVersion;

  String phase;

  String buildId;

  List<Object?> _toList() {
    return <Object?>[
      engineVersion,
      abiVersion,
      apiVersion,
      phase,
      buildId,
    ];
  }

  Object encode() {
    return _toList();  }

  static EngineInfo decode(Object result) {
    result as List<Object?>;
    return EngineInfo(
      engineVersion: result[0]! as String,
      abiVersion: result[1]! as int,
      apiVersion: result[2]! as int,
      phase: result[3]! as String,
      buildId: result[4]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! EngineInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(engineVersion, other.engineVersion) && _deepEquals(abiVersion, other.abiVersion) && _deepEquals(apiVersion, other.apiVersion) && _deepEquals(phase, other.phase) && _deepEquals(buildId, other.buildId);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'EngineInfo(engineVersion: $engineVersion, abiVersion: $abiVersion, apiVersion: $apiVersion, phase: $phase, buildId: $buildId)';
  }
}

class DiagnosticEvent {
  DiagnosticEvent({
    required this.sequence,
    required this.requestId,
    required this.kind,
  });

  int sequence;

  int requestId;

  int kind;

  List<Object?> _toList() {
    return <Object?>[
      sequence,
      requestId,
      kind,
    ];
  }

  Object encode() {
    return _toList();  }

  static DiagnosticEvent decode(Object result) {
    result as List<Object?>;
    return DiagnosticEvent(
      sequence: result[0]! as int,
      requestId: result[1]! as int,
      kind: result[2]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DiagnosticEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sequence, other.sequence) && _deepEquals(requestId, other.requestId) && _deepEquals(kind, other.kind);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'DiagnosticEvent(sequence: $sequence, requestId: $requestId, kind: $kind)';
  }
}

class EngineSnapshot {
  EngineSnapshot({
    required this.runtimeId,
    required this.cursor,
    required this.probeCount,
    required this.foundationState,
    required this.cursorReset,
    required this.events,
  });

  int runtimeId;

  int cursor;

  int probeCount;

  int foundationState;

  bool cursorReset;

  List<DiagnosticEvent> events;

  List<Object?> _toList() {
    return <Object?>[
      runtimeId,
      cursor,
      probeCount,
      foundationState,
      cursorReset,
      events,
    ];
  }

  Object encode() {
    return _toList();  }

  static EngineSnapshot decode(Object result) {
    result as List<Object?>;
    return EngineSnapshot(
      runtimeId: result[0]! as int,
      cursor: result[1]! as int,
      probeCount: result[2]! as int,
      foundationState: result[3]! as int,
      cursorReset: result[4]! as bool,
      events: (result[5]! as List<Object?>).cast<DiagnosticEvent>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! EngineSnapshot || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(runtimeId, other.runtimeId) && _deepEquals(cursor, other.cursor) && _deepEquals(probeCount, other.probeCount) && _deepEquals(foundationState, other.foundationState) && _deepEquals(cursorReset, other.cursorReset) && _deepEquals(events, other.events);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'EngineSnapshot(runtimeId: $runtimeId, cursor: $cursor, probeCount: $probeCount, foundationState: $foundationState, cursorReset: $cursorReset, events: $events)';
  }
}

class IdentityInfo {
  IdentityInfo({
    required this.fingerprint,
    required this.storage,
  });

  String fingerprint;

  String storage;

  List<Object?> _toList() {
    return <Object?>[
      fingerprint,
      storage,
    ];
  }

  Object encode() {
    return _toList();  }

  static IdentityInfo decode(Object result) {
    result as List<Object?>;
    return IdentityInfo(
      fingerprint: result[0]! as String,
      storage: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! IdentityInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(fingerprint, other.fingerprint) && _deepEquals(storage, other.storage);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'IdentityInfo(fingerprint: $fingerprint, storage: $storage)';
  }
}

class GroupInfo {
  GroupInfo({
    required this.configured,
    required this.epoch,
  });

  bool configured;

  int epoch;

  List<Object?> _toList() {
    return <Object?>[
      configured,
      epoch,
    ];
  }

  Object encode() {
    return _toList();  }

  static GroupInfo decode(Object result) {
    result as List<Object?>;
    return GroupInfo(
      configured: result[0]! as bool,
      epoch: result[1]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GroupInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(configured, other.configured) && _deepEquals(epoch, other.epoch);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'GroupInfo(configured: $configured, epoch: $epoch)';
  }
}

class BluetoothInfo {
  BluetoothInfo({
    required this.available,
    required this.authorized,
    required this.enabled,
    required this.active,
    required this.peerCount,
    required this.probeCount,
    required this.authenticated,
    required this.messageCount,
    required this.lastMessage,
    required this.detail,
  });

  bool available;

  bool authorized;

  bool enabled;

  bool active;

  int peerCount;

  int probeCount;

  bool authenticated;

  int messageCount;

  String lastMessage;

  String detail;

  List<Object?> _toList() {
    return <Object?>[
      available,
      authorized,
      enabled,
      active,
      peerCount,
      probeCount,
      authenticated,
      messageCount,
      lastMessage,
      detail,
    ];
  }

  Object encode() {
    return _toList();  }

  static BluetoothInfo decode(Object result) {
    result as List<Object?>;
    return BluetoothInfo(
      available: result[0]! as bool,
      authorized: result[1]! as bool,
      enabled: result[2]! as bool,
      active: result[3]! as bool,
      peerCount: result[4]! as int,
      probeCount: result[5]! as int,
      authenticated: result[6]! as bool,
      messageCount: result[7]! as int,
      lastMessage: result[8]! as String,
      detail: result[9]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BluetoothInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(available, other.available) && _deepEquals(authorized, other.authorized) && _deepEquals(enabled, other.enabled) && _deepEquals(active, other.active) && _deepEquals(peerCount, other.peerCount) && _deepEquals(probeCount, other.probeCount) && _deepEquals(authenticated, other.authenticated) && _deepEquals(messageCount, other.messageCount) && _deepEquals(lastMessage, other.lastMessage) && _deepEquals(detail, other.detail);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'BluetoothInfo(available: $available, authorized: $authorized, enabled: $enabled, active: $active, peerCount: $peerCount, probeCount: $probeCount, authenticated: $authenticated, messageCount: $messageCount, lastMessage: $lastMessage, detail: $detail)';
  }
}

/// A native-certified message revealed only after durable verification and a
/// local receipt commit. The origin is the roster member from the signed
/// object, never a radio address or product-provided field.
class VerifiedIncomingText {
  VerifiedIncomingText({
    required this.authorId,
    required this.objectId,
    required this.verifiedAtUnixSeconds,
    required this.body,
  });

  String authorId;

  String objectId;

  int verifiedAtUnixSeconds;

  String body;

  List<Object?> _toList() {
    return <Object?>[
      authorId,
      objectId,
      verifiedAtUnixSeconds,
      body,
    ];
  }

  Object encode() {
    return _toList();  }

  static VerifiedIncomingText decode(Object result) {
    result as List<Object?>;
    return VerifiedIncomingText(
      authorId: result[0]! as String,
      objectId: result[1]! as String,
      verifiedAtUnixSeconds: result[2]! as int,
      body: result[3]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VerifiedIncomingText || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(authorId, other.authorId) && _deepEquals(objectId, other.objectId) && _deepEquals(verifiedAtUnixSeconds, other.verifiedAtUnixSeconds) && _deepEquals(body, other.body);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'VerifiedIncomingText(authorId: $authorId, objectId: $objectId, verifiedAtUnixSeconds: $verifiedAtUnixSeconds, body: $body)';
  }
}

class VoiceInfo {
  VoiceInfo({
    required this.receivedCount,
    required this.lastDurationMillis,
    required this.ready,
    required this.detail,
  });

  int receivedCount;

  int lastDurationMillis;

  bool ready;

  String detail;

  List<Object?> _toList() {
    return <Object?>[
      receivedCount,
      lastDurationMillis,
      ready,
      detail,
    ];
  }

  Object encode() {
    return _toList();  }

  static VoiceInfo decode(Object result) {
    result as List<Object?>;
    return VoiceInfo(
      receivedCount: result[0]! as int,
      lastDurationMillis: result[1]! as int,
      ready: result[2]! as bool,
      detail: result[3]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VoiceInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(receivedCount, other.receivedCount) && _deepEquals(lastDurationMillis, other.lastDurationMillis) && _deepEquals(ready, other.ready) && _deepEquals(detail, other.detail);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'VoiceInfo(receivedCount: $receivedCount, lastDurationMillis: $lastDurationMillis, ready: $ready, detail: $detail)';
  }
}

/// Origin-local receipt evidence for one visible action. No object ID,
/// recipient identity, receipt or secret crosses into Flutter.
class DeliveryInfo {
  DeliveryInfo({
    required this.logicalId,
    required this.targetCount,
    required this.deliveredCount,
    required this.state,
  });

  String logicalId;

  int targetCount;

  int deliveredCount;

  String state;

  List<Object?> _toList() {
    return <Object?>[
      logicalId,
      targetCount,
      deliveredCount,
      state,
    ];
  }

  Object encode() {
    return _toList();  }

  static DeliveryInfo decode(Object result) {
    result as List<Object?>;
    return DeliveryInfo(
      logicalId: result[0]! as String,
      targetCount: result[1]! as int,
      deliveredCount: result[2]! as int,
      state: result[3]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DeliveryInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(logicalId, other.logicalId) && _deepEquals(targetCount, other.targetCount) && _deepEquals(deliveredCount, other.deliveredCount) && _deepEquals(state, other.state);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'DeliveryInfo(logicalId: $logicalId, targetCount: $targetCount, deliveredCount: $deliveredCount, state: $state)';
  }
}

/// Capability and discovery state for the direct Wi-Fi Aware radio.
/// It never exposes an IP address, SSID, router, or hotspot.
class AwareInfo {
  AwareInfo({
    required this.available,
    required this.enabled,
    required this.active,
    required this.peerCount,
    required this.maxPeers,
    required this.state,
    required this.detail,
  });

  bool available;

  bool enabled;

  bool active;

  int peerCount;

  int maxPeers;

  String state;

  String detail;

  List<Object?> _toList() {
    return <Object?>[
      available,
      enabled,
      active,
      peerCount,
      maxPeers,
      state,
      detail,
    ];
  }

  Object encode() {
    return _toList();  }

  static AwareInfo decode(Object result) {
    result as List<Object?>;
    return AwareInfo(
      available: result[0]! as bool,
      enabled: result[1]! as bool,
      active: result[2]! as bool,
      peerCount: result[3]! as int,
      maxPeers: result[4]! as int,
      state: result[5]! as String,
      detail: result[6]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AwareInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(available, other.available) && _deepEquals(enabled, other.enabled) && _deepEquals(active, other.active) && _deepEquals(peerCount, other.peerCount) && _deepEquals(maxPeers, other.maxPeers) && _deepEquals(state, other.state) && _deepEquals(detail, other.detail);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AwareInfo(available: $available, enabled: $enabled, active: $active, peerCount: $peerCount, maxPeers: $maxPeers, state: $state, detail: $detail)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is EngineInfo) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is DiagnosticEvent) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is EngineSnapshot) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is IdentityInfo) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is GroupInfo) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is BluetoothInfo) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is VerifiedIncomingText) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is VoiceInfo) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    }    else if (value is DeliveryInfo) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    }    else if (value is AwareInfo) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return EngineInfo.decode(readValue(buffer)!);
      case 130:
        return DiagnosticEvent.decode(readValue(buffer)!);
      case 131:
        return EngineSnapshot.decode(readValue(buffer)!);
      case 132:
        return IdentityInfo.decode(readValue(buffer)!);
      case 133:
        return GroupInfo.decode(readValue(buffer)!);
      case 134:
        return BluetoothInfo.decode(readValue(buffer)!);
      case 135:
        return VerifiedIncomingText.decode(readValue(buffer)!);
      case 136:
        return VoiceInfo.decode(readValue(buffer)!);
      case 137:
        return DeliveryInfo.decode(readValue(buffer)!);
      case 138:
        return AwareInfo.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class MeshHostApi {
  /// Constructor for [MeshHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  MeshHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<EngineInfo> engineInfo() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.mesh_host.MeshHostApi.engineInfo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as EngineInfo;
  }

  Future<IdentityInfo> prepareIdentity() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.mesh_host.MeshHostApi.prepareIdentity$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as IdentityInfo;
  }

  Future<GroupInfo> groupInfo() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.mesh_host.MeshHostApi.groupInfo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as GroupInfo;
  }

  Future<GroupInfo> createGroup() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.mesh_host.MeshHostApi.createGroup$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as GroupInfo;
  }

  Future<Uint8List> exportInvitation() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.mesh_host.MeshHostApi.exportInvitation$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as Uint8List;
  }

  Future<Uint8List> createEnrollmentRequest(Uint8List invitation) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.mesh_host.MeshHostApi.createEnrollmentRequest$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[invitation]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as Uint8List;
  }

  Future<Uint8List> issueEnrollment(Uint8List request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.mesh_host.MeshHostApi.issueEnrollment$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as Uint8List;
  }

  Future<GroupInfo> installPolicy(Uint8List policy) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.mesh_host.MeshHostApi.installPolicy$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[policy]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as GroupInfo;
  }

  Future<BluetoothInfo> bluetoothInfo() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.mesh_host.MeshHostApi.bluetoothInfo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as BluetoothInfo;
  }

  Future<BluetoothInfo> prepareBluetooth() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.mesh_host.MeshHostApi.prepareBluetooth$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as BluetoothInfo;
  }

  Future<BluetoothInfo> startBluetoothDiscovery() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.mesh_host.MeshHostApi.startBluetoothDiscovery$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as BluetoothInfo;
  }

  Future<BluetoothInfo> stopBluetoothDiscovery() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.mesh_host.MeshHostApi.stopBluetoothDiscovery$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as BluetoothInfo;
  }

  Future<AwareInfo> awareInfo() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.mesh_host.MeshHostApi.awareInfo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as AwareInfo;
  }

  Future<AwareInfo> startAwareDiscovery() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.mesh_host.MeshHostApi.startAwareDiscovery$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as AwareInfo;
  }

  Future<AwareInfo> stopAwareDiscovery() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.mesh_host.MeshHostApi.stopAwareDiscovery$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as AwareInfo;
  }

  Future<bool> sendText(String message, String logicalId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.mesh_host.MeshHostApi.sendText$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[message, logicalId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<DeliveryInfo> deliveryInfo(String logicalId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.mesh_host.MeshHostApi.deliveryInfo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[logicalId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as DeliveryInfo;
  }

  Future<List<VerifiedIncomingText>> drainVerifiedIncomingText() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.mesh_host.MeshHostApi.drainVerifiedIncomingText$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<VerifiedIncomingText>();
  }

  Future<VoiceInfo> voiceInfo() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.mesh_host.MeshHostApi.voiceInfo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as VoiceInfo;
  }

  Future<bool> sendVoice(Uint8List audio, int durationMillis, String logicalId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.mesh_host.MeshHostApi.sendVoice$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[audio, durationMillis, logicalId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<bool> playLastVoice() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.mesh_host.MeshHostApi.playLastVoice$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<EngineSnapshot> subscribe(int cursor) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.mesh_host.MeshHostApi.subscribe$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[cursor]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as EngineSnapshot;
  }

  Future<EngineSnapshot> verifyBridge(int requestId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.mesh_host.MeshHostApi.verifyBridge$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[requestId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as EngineSnapshot;
  }
}
