// Autogenerated from Pigeon (v28.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.frazko.mesh_host

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object MeshApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Generated class from Pigeon that represents data sent in messages. */
data class EngineInfo (
  val engineVersion: String,
  val abiVersion: Long,
  val apiVersion: Long,
  val phase: String,
  val buildId: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): EngineInfo {
      val engineVersion = pigeonVar_list[0] as String
      val abiVersion = pigeonVar_list[1] as Long
      val apiVersion = pigeonVar_list[2] as Long
      val phase = pigeonVar_list[3] as String
      val buildId = pigeonVar_list[4] as String
      return EngineInfo(engineVersion, abiVersion, apiVersion, phase, buildId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      engineVersion,
      abiVersion,
      apiVersion,
      phase,
      buildId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as EngineInfo
    return MeshApiPigeonUtils.deepEquals(this.engineVersion, other.engineVersion) && MeshApiPigeonUtils.deepEquals(this.abiVersion, other.abiVersion) && MeshApiPigeonUtils.deepEquals(this.apiVersion, other.apiVersion) && MeshApiPigeonUtils.deepEquals(this.phase, other.phase) && MeshApiPigeonUtils.deepEquals(this.buildId, other.buildId)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MeshApiPigeonUtils.deepHash(this.engineVersion)
    result = 31 * result + MeshApiPigeonUtils.deepHash(this.abiVersion)
    result = 31 * result + MeshApiPigeonUtils.deepHash(this.apiVersion)
    result = 31 * result + MeshApiPigeonUtils.deepHash(this.phase)
    result = 31 * result + MeshApiPigeonUtils.deepHash(this.buildId)
    return result
  }
  override fun toString(): String {
    return "EngineInfo(engineVersion=$engineVersion, abiVersion=$abiVersion, apiVersion=$apiVersion, phase=$phase, buildId=$buildId)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DiagnosticEvent (
  val sequence: Long,
  val requestId: Long,
  val kind: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DiagnosticEvent {
      val sequence = pigeonVar_list[0] as Long
      val requestId = pigeonVar_list[1] as Long
      val kind = pigeonVar_list[2] as Long
      return DiagnosticEvent(sequence, requestId, kind)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sequence,
      requestId,
      kind,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as DiagnosticEvent
    return MeshApiPigeonUtils.deepEquals(this.sequence, other.sequence) && MeshApiPigeonUtils.deepEquals(this.requestId, other.requestId) && MeshApiPigeonUtils.deepEquals(this.kind, other.kind)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MeshApiPigeonUtils.deepHash(this.sequence)
    result = 31 * result + MeshApiPigeonUtils.deepHash(this.requestId)
    result = 31 * result + MeshApiPigeonUtils.deepHash(this.kind)
    return result
  }
  override fun toString(): String {
    return "DiagnosticEvent(sequence=$sequence, requestId=$requestId, kind=$kind)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class EngineSnapshot (
  val runtimeId: Long,
  val cursor: Long,
  val probeCount: Long,
  val foundationState: Long,
  val cursorReset: Boolean,
  val events: List<DiagnosticEvent>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): EngineSnapshot {
      val runtimeId = pigeonVar_list[0] as Long
      val cursor = pigeonVar_list[1] as Long
      val probeCount = pigeonVar_list[2] as Long
      val foundationState = pigeonVar_list[3] as Long
      val cursorReset = pigeonVar_list[4] as Boolean
      val events = pigeonVar_list[5] as List<DiagnosticEvent>
      return EngineSnapshot(runtimeId, cursor, probeCount, foundationState, cursorReset, events)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      runtimeId,
      cursor,
      probeCount,
      foundationState,
      cursorReset,
      events,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as EngineSnapshot
    return MeshApiPigeonUtils.deepEquals(this.runtimeId, other.runtimeId) && MeshApiPigeonUtils.deepEquals(this.cursor, other.cursor) && MeshApiPigeonUtils.deepEquals(this.probeCount, other.probeCount) && MeshApiPigeonUtils.deepEquals(this.foundationState, other.foundationState) && MeshApiPigeonUtils.deepEquals(this.cursorReset, other.cursorReset) && MeshApiPigeonUtils.deepEquals(this.events, other.events)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MeshApiPigeonUtils.deepHash(this.runtimeId)
    result = 31 * result + MeshApiPigeonUtils.deepHash(this.cursor)
    result = 31 * result + MeshApiPigeonUtils.deepHash(this.probeCount)
    result = 31 * result + MeshApiPigeonUtils.deepHash(this.foundationState)
    result = 31 * result + MeshApiPigeonUtils.deepHash(this.cursorReset)
    result = 31 * result + MeshApiPigeonUtils.deepHash(this.events)
    return result
  }
  override fun toString(): String {
    return "EngineSnapshot(runtimeId=$runtimeId, cursor=$cursor, probeCount=$probeCount, foundationState=$foundationState, cursorReset=$cursorReset, events=$events)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class IdentityInfo (
  val fingerprint: String,
  val storage: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): IdentityInfo {
      val fingerprint = pigeonVar_list[0] as String
      val storage = pigeonVar_list[1] as String
      return IdentityInfo(fingerprint, storage)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      fingerprint,
      storage,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as IdentityInfo
    return MeshApiPigeonUtils.deepEquals(this.fingerprint, other.fingerprint) && MeshApiPigeonUtils.deepEquals(this.storage, other.storage)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MeshApiPigeonUtils.deepHash(this.fingerprint)
    result = 31 * result + MeshApiPigeonUtils.deepHash(this.storage)
    return result
  }
  override fun toString(): String {
    return "IdentityInfo(fingerprint=$fingerprint, storage=$storage)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class GroupInfo (
  val configured: Boolean,
  val epoch: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): GroupInfo {
      val configured = pigeonVar_list[0] as Boolean
      val epoch = pigeonVar_list[1] as Long
      return GroupInfo(configured, epoch)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      configured,
      epoch,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as GroupInfo
    return MeshApiPigeonUtils.deepEquals(this.configured, other.configured) && MeshApiPigeonUtils.deepEquals(this.epoch, other.epoch)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MeshApiPigeonUtils.deepHash(this.configured)
    result = 31 * result + MeshApiPigeonUtils.deepHash(this.epoch)
    return result
  }
  override fun toString(): String {
    return "GroupInfo(configured=$configured, epoch=$epoch)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BluetoothInfo (
  val available: Boolean,
  val authorized: Boolean,
  val enabled: Boolean,
  val active: Boolean,
  val peerCount: Long,
  val probeCount: Long,
  val authenticated: Boolean,
  val messageCount: Long,
  val lastMessage: String,
  val detail: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BluetoothInfo {
      val available = pigeonVar_list[0] as Boolean
      val authorized = pigeonVar_list[1] as Boolean
      val enabled = pigeonVar_list[2] as Boolean
      val active = pigeonVar_list[3] as Boolean
      val peerCount = pigeonVar_list[4] as Long
      val probeCount = pigeonVar_list[5] as Long
      val authenticated = pigeonVar_list[6] as Boolean
      val messageCount = pigeonVar_list[7] as Long
      val lastMessage = pigeonVar_list[8] as String
      val detail = pigeonVar_list[9] as String
      return BluetoothInfo(available, authorized, enabled, active, peerCount, probeCount, authenticated, messageCount, lastMessage, detail)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      available,
      authorized,
      enabled,
      active,
      peerCount,
      probeCount,
      authenticated,
      messageCount,
      lastMessage,
      detail,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BluetoothInfo
    return MeshApiPigeonUtils.deepEquals(this.available, other.available) && MeshApiPigeonUtils.deepEquals(this.authorized, other.authorized) && MeshApiPigeonUtils.deepEquals(this.enabled, other.enabled) && MeshApiPigeonUtils.deepEquals(this.active, other.active) && MeshApiPigeonUtils.deepEquals(this.peerCount, other.peerCount) && MeshApiPigeonUtils.deepEquals(this.probeCount, other.probeCount) && MeshApiPigeonUtils.deepEquals(this.authenticated, other.authenticated) && MeshApiPigeonUtils.deepEquals(this.messageCount, other.messageCount) && MeshApiPigeonUtils.deepEquals(this.lastMessage, other.lastMessage) && MeshApiPigeonUtils.deepEquals(this.detail, other.detail)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MeshApiPigeonUtils.deepHash(this.available)
    result = 31 * result + MeshApiPigeonUtils.deepHash(this.authorized)
    result = 31 * result + MeshApiPigeonUtils.deepHash(this.enabled)
    result = 31 * result + MeshApiPigeonUtils.deepHash(this.active)
    result = 31 * result + MeshApiPigeonUtils.deepHash(this.peerCount)
    result = 31 * result + MeshApiPigeonUtils.deepHash(this.probeCount)
    result = 31 * result + MeshApiPigeonUtils.deepHash(this.authenticated)
    result = 31 * result + MeshApiPigeonUtils.deepHash(this.messageCount)
    result = 31 * result + MeshApiPigeonUtils.deepHash(this.lastMessage)
    result = 31 * result + MeshApiPigeonUtils.deepHash(this.detail)
    return result
  }
  override fun toString(): String {
    return "BluetoothInfo(available=$available, authorized=$authorized, enabled=$enabled, active=$active, peerCount=$peerCount, probeCount=$probeCount, authenticated=$authenticated, messageCount=$messageCount, lastMessage=$lastMessage, detail=$detail)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VoiceInfo (
  val receivedCount: Long,
  val lastDurationMillis: Long,
  val ready: Boolean,
  val detail: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VoiceInfo {
      val receivedCount = pigeonVar_list[0] as Long
      val lastDurationMillis = pigeonVar_list[1] as Long
      val ready = pigeonVar_list[2] as Boolean
      val detail = pigeonVar_list[3] as String
      return VoiceInfo(receivedCount, lastDurationMillis, ready, detail)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      receivedCount,
      lastDurationMillis,
      ready,
      detail,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as VoiceInfo
    return MeshApiPigeonUtils.deepEquals(this.receivedCount, other.receivedCount) && MeshApiPigeonUtils.deepEquals(this.lastDurationMillis, other.lastDurationMillis) && MeshApiPigeonUtils.deepEquals(this.ready, other.ready) && MeshApiPigeonUtils.deepEquals(this.detail, other.detail)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MeshApiPigeonUtils.deepHash(this.receivedCount)
    result = 31 * result + MeshApiPigeonUtils.deepHash(this.lastDurationMillis)
    result = 31 * result + MeshApiPigeonUtils.deepHash(this.ready)
    result = 31 * result + MeshApiPigeonUtils.deepHash(this.detail)
    return result
  }
  override fun toString(): String {
    return "VoiceInfo(receivedCount=$receivedCount, lastDurationMillis=$lastDurationMillis, ready=$ready, detail=$detail)"
  }
}

/**
 * Origin-local receipt evidence for one visible action. No object ID,
 * recipient identity, receipt or secret crosses into Flutter.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class DeliveryInfo (
  val logicalId: String,
  val targetCount: Long,
  val deliveredCount: Long,
  val state: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DeliveryInfo {
      val logicalId = pigeonVar_list[0] as String
      val targetCount = pigeonVar_list[1] as Long
      val deliveredCount = pigeonVar_list[2] as Long
      val state = pigeonVar_list[3] as String
      return DeliveryInfo(logicalId, targetCount, deliveredCount, state)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      logicalId,
      targetCount,
      deliveredCount,
      state,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as DeliveryInfo
    return MeshApiPigeonUtils.deepEquals(this.logicalId, other.logicalId) && MeshApiPigeonUtils.deepEquals(this.targetCount, other.targetCount) && MeshApiPigeonUtils.deepEquals(this.deliveredCount, other.deliveredCount) && MeshApiPigeonUtils.deepEquals(this.state, other.state)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MeshApiPigeonUtils.deepHash(this.logicalId)
    result = 31 * result + MeshApiPigeonUtils.deepHash(this.targetCount)
    result = 31 * result + MeshApiPigeonUtils.deepHash(this.deliveredCount)
    result = 31 * result + MeshApiPigeonUtils.deepHash(this.state)
    return result
  }
  override fun toString(): String {
    return "DeliveryInfo(logicalId=$logicalId, targetCount=$targetCount, deliveredCount=$deliveredCount, state=$state)"
  }
}

/**
 * Capability and discovery state for the direct Wi-Fi Aware radio.
 * It never exposes an IP address, SSID, router, or hotspot.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AwareInfo (
  val available: Boolean,
  val enabled: Boolean,
  val active: Boolean,
  val peerCount: Long,
  val maxPeers: Long,
  val state: String,
  val detail: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AwareInfo {
      val available = pigeonVar_list[0] as Boolean
      val enabled = pigeonVar_list[1] as Boolean
      val active = pigeonVar_list[2] as Boolean
      val peerCount = pigeonVar_list[3] as Long
      val maxPeers = pigeonVar_list[4] as Long
      val state = pigeonVar_list[5] as String
      val detail = pigeonVar_list[6] as String
      return AwareInfo(available, enabled, active, peerCount, maxPeers, state, detail)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      available,
      enabled,
      active,
      peerCount,
      maxPeers,
      state,
      detail,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AwareInfo
    return MeshApiPigeonUtils.deepEquals(this.available, other.available) && MeshApiPigeonUtils.deepEquals(this.enabled, other.enabled) && MeshApiPigeonUtils.deepEquals(this.active, other.active) && MeshApiPigeonUtils.deepEquals(this.peerCount, other.peerCount) && MeshApiPigeonUtils.deepEquals(this.maxPeers, other.maxPeers) && MeshApiPigeonUtils.deepEquals(this.state, other.state) && MeshApiPigeonUtils.deepEquals(this.detail, other.detail)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MeshApiPigeonUtils.deepHash(this.available)
    result = 31 * result + MeshApiPigeonUtils.deepHash(this.enabled)
    result = 31 * result + MeshApiPigeonUtils.deepHash(this.active)
    result = 31 * result + MeshApiPigeonUtils.deepHash(this.peerCount)
    result = 31 * result + MeshApiPigeonUtils.deepHash(this.maxPeers)
    result = 31 * result + MeshApiPigeonUtils.deepHash(this.state)
    result = 31 * result + MeshApiPigeonUtils.deepHash(this.detail)
    return result
  }
  override fun toString(): String {
    return "AwareInfo(available=$available, enabled=$enabled, active=$active, peerCount=$peerCount, maxPeers=$maxPeers, state=$state, detail=$detail)"
  }
}
private open class MeshApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          EngineInfo.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DiagnosticEvent.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          EngineSnapshot.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          IdentityInfo.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          GroupInfo.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BluetoothInfo.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VoiceInfo.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DeliveryInfo.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AwareInfo.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is EngineInfo -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is DiagnosticEvent -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is EngineSnapshot -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is IdentityInfo -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is GroupInfo -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is BluetoothInfo -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is VoiceInfo -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is DeliveryInfo -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is AwareInfo -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface MeshHostApi {
  suspend fun engineInfo(): EngineInfo
  suspend fun prepareIdentity(): IdentityInfo
  suspend fun groupInfo(): GroupInfo
  suspend fun createGroup(): GroupInfo
  suspend fun exportInvitation(): ByteArray
  suspend fun createEnrollmentRequest(invitation: ByteArray): ByteArray
  suspend fun issueEnrollment(request: ByteArray): ByteArray
  suspend fun installPolicy(policy: ByteArray): GroupInfo
  suspend fun bluetoothInfo(): BluetoothInfo
  suspend fun prepareBluetooth(): BluetoothInfo
  suspend fun startBluetoothDiscovery(): BluetoothInfo
  suspend fun stopBluetoothDiscovery(): BluetoothInfo
  suspend fun awareInfo(): AwareInfo
  suspend fun startAwareDiscovery(): AwareInfo
  suspend fun stopAwareDiscovery(): AwareInfo
  suspend fun sendText(message: String, logicalId: String): Boolean
  suspend fun deliveryInfo(logicalId: String): DeliveryInfo
  suspend fun voiceInfo(): VoiceInfo
  suspend fun sendVoice(audio: ByteArray, durationMillis: Long, logicalId: String): Boolean
  suspend fun playLastVoice(): Boolean
  suspend fun subscribe(cursor: Long): EngineSnapshot
  suspend fun verifyBridge(requestId: Long): EngineSnapshot

  companion object {
    /** The codec used by MeshHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MeshApiPigeonCodec()
    }
    /** Sets up an instance of `MeshHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: MeshHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mesh_host.MeshHostApi.engineInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.engineInfo())
              } catch (exception: Throwable) {
                MeshApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mesh_host.MeshHostApi.prepareIdentity$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.prepareIdentity())
              } catch (exception: Throwable) {
                MeshApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mesh_host.MeshHostApi.groupInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.groupInfo())
              } catch (exception: Throwable) {
                MeshApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mesh_host.MeshHostApi.createGroup$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.createGroup())
              } catch (exception: Throwable) {
                MeshApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mesh_host.MeshHostApi.exportInvitation$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.exportInvitation())
              } catch (exception: Throwable) {
                MeshApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mesh_host.MeshHostApi.createEnrollmentRequest$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val invitationArg = args[0] as ByteArray
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.createEnrollmentRequest(invitationArg))
              } catch (exception: Throwable) {
                MeshApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mesh_host.MeshHostApi.issueEnrollment$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as ByteArray
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.issueEnrollment(requestArg))
              } catch (exception: Throwable) {
                MeshApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mesh_host.MeshHostApi.installPolicy$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val policyArg = args[0] as ByteArray
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.installPolicy(policyArg))
              } catch (exception: Throwable) {
                MeshApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mesh_host.MeshHostApi.bluetoothInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.bluetoothInfo())
              } catch (exception: Throwable) {
                MeshApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mesh_host.MeshHostApi.prepareBluetooth$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.prepareBluetooth())
              } catch (exception: Throwable) {
                MeshApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mesh_host.MeshHostApi.startBluetoothDiscovery$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.startBluetoothDiscovery())
              } catch (exception: Throwable) {
                MeshApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mesh_host.MeshHostApi.stopBluetoothDiscovery$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.stopBluetoothDiscovery())
              } catch (exception: Throwable) {
                MeshApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mesh_host.MeshHostApi.awareInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.awareInfo())
              } catch (exception: Throwable) {
                MeshApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mesh_host.MeshHostApi.startAwareDiscovery$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.startAwareDiscovery())
              } catch (exception: Throwable) {
                MeshApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mesh_host.MeshHostApi.stopAwareDiscovery$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.stopAwareDiscovery())
              } catch (exception: Throwable) {
                MeshApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mesh_host.MeshHostApi.sendText$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val messageArg = args[0] as String
            val logicalIdArg = args[1] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.sendText(messageArg, logicalIdArg))
              } catch (exception: Throwable) {
                MeshApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mesh_host.MeshHostApi.deliveryInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val logicalIdArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.deliveryInfo(logicalIdArg))
              } catch (exception: Throwable) {
                MeshApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mesh_host.MeshHostApi.voiceInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.voiceInfo())
              } catch (exception: Throwable) {
                MeshApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mesh_host.MeshHostApi.sendVoice$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val audioArg = args[0] as ByteArray
            val durationMillisArg = args[1] as Long
            val logicalIdArg = args[2] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.sendVoice(audioArg, durationMillisArg, logicalIdArg))
              } catch (exception: Throwable) {
                MeshApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mesh_host.MeshHostApi.playLastVoice$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.playLastVoice())
              } catch (exception: Throwable) {
                MeshApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mesh_host.MeshHostApi.subscribe$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val cursorArg = args[0] as Long
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.subscribe(cursorArg))
              } catch (exception: Throwable) {
                MeshApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mesh_host.MeshHostApi.verifyBridge$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as Long
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.verifyBridge(requestIdArg))
              } catch (exception: Throwable) {
                MeshApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
