// Autogenerated from Pigeon (v28.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum MeshApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Generated class from Pigeon that represents data sent in messages.
struct EngineInfo: Hashable, CustomStringConvertible {
  var engineVersion: String
  var abiVersion: Int64
  var apiVersion: Int64
  var phase: String
  var buildId: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> EngineInfo? {
    let engineVersion = pigeonVar_list[0] as! String
    let abiVersion = pigeonVar_list[1] as! Int64
    let apiVersion = pigeonVar_list[2] as! Int64
    let phase = pigeonVar_list[3] as! String
    let buildId = pigeonVar_list[4] as! String

    return EngineInfo(
      engineVersion: engineVersion,
      abiVersion: abiVersion,
      apiVersion: apiVersion,
      phase: phase,
      buildId: buildId
    )
  }
  func toList() -> [Any?] {
    return [
      engineVersion,
      abiVersion,
      apiVersion,
      phase,
      buildId,
    ]
  }
  static func == (lhs: EngineInfo, rhs: EngineInfo) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MeshApiPigeonInternal.deepEquals(lhs.engineVersion, rhs.engineVersion) && MeshApiPigeonInternal.deepEquals(lhs.abiVersion, rhs.abiVersion) && MeshApiPigeonInternal.deepEquals(lhs.apiVersion, rhs.apiVersion) && MeshApiPigeonInternal.deepEquals(lhs.phase, rhs.phase) && MeshApiPigeonInternal.deepEquals(lhs.buildId, rhs.buildId)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("EngineInfo")
    MeshApiPigeonInternal.deepHash(value: engineVersion, hasher: &hasher)
    MeshApiPigeonInternal.deepHash(value: abiVersion, hasher: &hasher)
    MeshApiPigeonInternal.deepHash(value: apiVersion, hasher: &hasher)
    MeshApiPigeonInternal.deepHash(value: phase, hasher: &hasher)
    MeshApiPigeonInternal.deepHash(value: buildId, hasher: &hasher)
  }

  public var description: String {
    return "EngineInfo(engineVersion: \(String(describing: engineVersion)), abiVersion: \(String(describing: abiVersion)), apiVersion: \(String(describing: apiVersion)), phase: \(String(describing: phase)), buildId: \(String(describing: buildId)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct DiagnosticEvent: Hashable, CustomStringConvertible {
  var sequence: Int64
  var requestId: Int64
  var kind: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DiagnosticEvent? {
    let sequence = pigeonVar_list[0] as! Int64
    let requestId = pigeonVar_list[1] as! Int64
    let kind = pigeonVar_list[2] as! Int64

    return DiagnosticEvent(
      sequence: sequence,
      requestId: requestId,
      kind: kind
    )
  }
  func toList() -> [Any?] {
    return [
      sequence,
      requestId,
      kind,
    ]
  }
  static func == (lhs: DiagnosticEvent, rhs: DiagnosticEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MeshApiPigeonInternal.deepEquals(lhs.sequence, rhs.sequence) && MeshApiPigeonInternal.deepEquals(lhs.requestId, rhs.requestId) && MeshApiPigeonInternal.deepEquals(lhs.kind, rhs.kind)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("DiagnosticEvent")
    MeshApiPigeonInternal.deepHash(value: sequence, hasher: &hasher)
    MeshApiPigeonInternal.deepHash(value: requestId, hasher: &hasher)
    MeshApiPigeonInternal.deepHash(value: kind, hasher: &hasher)
  }

  public var description: String {
    return "DiagnosticEvent(sequence: \(String(describing: sequence)), requestId: \(String(describing: requestId)), kind: \(String(describing: kind)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct EngineSnapshot: Hashable, CustomStringConvertible {
  var runtimeId: Int64
  var cursor: Int64
  var probeCount: Int64
  var foundationState: Int64
  var cursorReset: Bool
  var events: [DiagnosticEvent]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> EngineSnapshot? {
    let runtimeId = pigeonVar_list[0] as! Int64
    let cursor = pigeonVar_list[1] as! Int64
    let probeCount = pigeonVar_list[2] as! Int64
    let foundationState = pigeonVar_list[3] as! Int64
    let cursorReset = pigeonVar_list[4] as! Bool
    let events = pigeonVar_list[5] as! [DiagnosticEvent]

    return EngineSnapshot(
      runtimeId: runtimeId,
      cursor: cursor,
      probeCount: probeCount,
      foundationState: foundationState,
      cursorReset: cursorReset,
      events: events
    )
  }
  func toList() -> [Any?] {
    return [
      runtimeId,
      cursor,
      probeCount,
      foundationState,
      cursorReset,
      events,
    ]
  }
  static func == (lhs: EngineSnapshot, rhs: EngineSnapshot) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MeshApiPigeonInternal.deepEquals(lhs.runtimeId, rhs.runtimeId) && MeshApiPigeonInternal.deepEquals(lhs.cursor, rhs.cursor) && MeshApiPigeonInternal.deepEquals(lhs.probeCount, rhs.probeCount) && MeshApiPigeonInternal.deepEquals(lhs.foundationState, rhs.foundationState) && MeshApiPigeonInternal.deepEquals(lhs.cursorReset, rhs.cursorReset) && MeshApiPigeonInternal.deepEquals(lhs.events, rhs.events)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("EngineSnapshot")
    MeshApiPigeonInternal.deepHash(value: runtimeId, hasher: &hasher)
    MeshApiPigeonInternal.deepHash(value: cursor, hasher: &hasher)
    MeshApiPigeonInternal.deepHash(value: probeCount, hasher: &hasher)
    MeshApiPigeonInternal.deepHash(value: foundationState, hasher: &hasher)
    MeshApiPigeonInternal.deepHash(value: cursorReset, hasher: &hasher)
    MeshApiPigeonInternal.deepHash(value: events, hasher: &hasher)
  }

  public var description: String {
    return "EngineSnapshot(runtimeId: \(String(describing: runtimeId)), cursor: \(String(describing: cursor)), probeCount: \(String(describing: probeCount)), foundationState: \(String(describing: foundationState)), cursorReset: \(String(describing: cursorReset)), events: \(String(describing: events)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct IdentityInfo: Hashable, CustomStringConvertible {
  var fingerprint: String
  var storage: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> IdentityInfo? {
    let fingerprint = pigeonVar_list[0] as! String
    let storage = pigeonVar_list[1] as! String

    return IdentityInfo(
      fingerprint: fingerprint,
      storage: storage
    )
  }
  func toList() -> [Any?] {
    return [
      fingerprint,
      storage,
    ]
  }
  static func == (lhs: IdentityInfo, rhs: IdentityInfo) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MeshApiPigeonInternal.deepEquals(lhs.fingerprint, rhs.fingerprint) && MeshApiPigeonInternal.deepEquals(lhs.storage, rhs.storage)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("IdentityInfo")
    MeshApiPigeonInternal.deepHash(value: fingerprint, hasher: &hasher)
    MeshApiPigeonInternal.deepHash(value: storage, hasher: &hasher)
  }

  public var description: String {
    return "IdentityInfo(fingerprint: \(String(describing: fingerprint)), storage: \(String(describing: storage)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct GroupInfo: Hashable, CustomStringConvertible {
  var configured: Bool
  var epoch: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> GroupInfo? {
    let configured = pigeonVar_list[0] as! Bool
    let epoch = pigeonVar_list[1] as! Int64

    return GroupInfo(
      configured: configured,
      epoch: epoch
    )
  }
  func toList() -> [Any?] {
    return [
      configured,
      epoch,
    ]
  }
  static func == (lhs: GroupInfo, rhs: GroupInfo) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MeshApiPigeonInternal.deepEquals(lhs.configured, rhs.configured) && MeshApiPigeonInternal.deepEquals(lhs.epoch, rhs.epoch)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("GroupInfo")
    MeshApiPigeonInternal.deepHash(value: configured, hasher: &hasher)
    MeshApiPigeonInternal.deepHash(value: epoch, hasher: &hasher)
  }

  public var description: String {
    return "GroupInfo(configured: \(String(describing: configured)), epoch: \(String(describing: epoch)))"
  }
}

/// A Field-author proof for a canonical cloud-relay envelope. The group identifier, epoch and
/// signature are public verification data; keys and roster stay native.
///
/// Generated class from Pigeon that represents data sent in messages.
struct CloudRelayProof: Hashable, CustomStringConvertible {
  var groupId: FlutterStandardTypedData
  var epoch: Int64
  var signature: FlutterStandardTypedData


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CloudRelayProof? {
    let groupId = pigeonVar_list[0] as! FlutterStandardTypedData
    let epoch = pigeonVar_list[1] as! Int64
    let signature = pigeonVar_list[2] as! FlutterStandardTypedData

    return CloudRelayProof(
      groupId: groupId,
      epoch: epoch,
      signature: signature
    )
  }
  func toList() -> [Any?] {
    return [
      groupId,
      epoch,
      signature,
    ]
  }
  static func == (lhs: CloudRelayProof, rhs: CloudRelayProof) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MeshApiPigeonInternal.deepEquals(lhs.groupId, rhs.groupId) && MeshApiPigeonInternal.deepEquals(lhs.epoch, rhs.epoch) && MeshApiPigeonInternal.deepEquals(lhs.signature, rhs.signature)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CloudRelayProof")
    MeshApiPigeonInternal.deepHash(value: groupId, hasher: &hasher)
    MeshApiPigeonInternal.deepHash(value: epoch, hasher: &hasher)
    MeshApiPigeonInternal.deepHash(value: signature, hasher: &hasher)
  }

  public var description: String {
    return "CloudRelayProof(groupId: \(String(describing: groupId)), epoch: \(String(describing: epoch)), signature: \(String(describing: signature)))"
  }
}

/// Product-owned admission boundary for automatic enrollment. Member IDs are
/// public 32-byte fingerprints encoded as lowercase hex. The native host still
/// verifies the request signature before comparing it with this roster.
///
/// Generated class from Pigeon that represents data sent in messages.
struct EnrollmentAccessPolicy: Hashable, CustomStringConvertible {
  /// Opaque, product-owned 128-bit scope. It selects a separate encrypted
  /// Field store so policies from two product groups cannot share a radio
  /// group merely because they use the same phone identity.
  var scopeId: String
  var authorizedMemberIds: [String]
  var authorityEnabled: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> EnrollmentAccessPolicy? {
    let scopeId = pigeonVar_list[0] as! String
    let authorizedMemberIds = pigeonVar_list[1] as! [String]
    let authorityEnabled = pigeonVar_list[2] as! Bool

    return EnrollmentAccessPolicy(
      scopeId: scopeId,
      authorizedMemberIds: authorizedMemberIds,
      authorityEnabled: authorityEnabled
    )
  }
  func toList() -> [Any?] {
    return [
      scopeId,
      authorizedMemberIds,
      authorityEnabled,
    ]
  }
  static func == (lhs: EnrollmentAccessPolicy, rhs: EnrollmentAccessPolicy) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MeshApiPigeonInternal.deepEquals(lhs.scopeId, rhs.scopeId) && MeshApiPigeonInternal.deepEquals(lhs.authorizedMemberIds, rhs.authorizedMemberIds) && MeshApiPigeonInternal.deepEquals(lhs.authorityEnabled, rhs.authorityEnabled)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("EnrollmentAccessPolicy")
    MeshApiPigeonInternal.deepHash(value: scopeId, hasher: &hasher)
    MeshApiPigeonInternal.deepHash(value: authorizedMemberIds, hasher: &hasher)
    MeshApiPigeonInternal.deepHash(value: authorityEnabled, hasher: &hasher)
  }

  public var description: String {
    return "EnrollmentAccessPolicy(scopeId: \(String(describing: scopeId)), authorizedMemberIds: \(String(describing: authorizedMemberIds)), authorityEnabled: \(String(describing: authorityEnabled)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BluetoothInfo: Hashable, CustomStringConvertible {
  var available: Bool
  var authorized: Bool
  var enabled: Bool
  var active: Bool
  var peerCount: Int64
  var probeCount: Int64
  var authenticated: Bool
  var messageCount: Int64
  var lastMessage: String
  var detail: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BluetoothInfo? {
    let available = pigeonVar_list[0] as! Bool
    let authorized = pigeonVar_list[1] as! Bool
    let enabled = pigeonVar_list[2] as! Bool
    let active = pigeonVar_list[3] as! Bool
    let peerCount = pigeonVar_list[4] as! Int64
    let probeCount = pigeonVar_list[5] as! Int64
    let authenticated = pigeonVar_list[6] as! Bool
    let messageCount = pigeonVar_list[7] as! Int64
    let lastMessage = pigeonVar_list[8] as! String
    let detail = pigeonVar_list[9] as! String

    return BluetoothInfo(
      available: available,
      authorized: authorized,
      enabled: enabled,
      active: active,
      peerCount: peerCount,
      probeCount: probeCount,
      authenticated: authenticated,
      messageCount: messageCount,
      lastMessage: lastMessage,
      detail: detail
    )
  }
  func toList() -> [Any?] {
    return [
      available,
      authorized,
      enabled,
      active,
      peerCount,
      probeCount,
      authenticated,
      messageCount,
      lastMessage,
      detail,
    ]
  }
  static func == (lhs: BluetoothInfo, rhs: BluetoothInfo) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MeshApiPigeonInternal.deepEquals(lhs.available, rhs.available) && MeshApiPigeonInternal.deepEquals(lhs.authorized, rhs.authorized) && MeshApiPigeonInternal.deepEquals(lhs.enabled, rhs.enabled) && MeshApiPigeonInternal.deepEquals(lhs.active, rhs.active) && MeshApiPigeonInternal.deepEquals(lhs.peerCount, rhs.peerCount) && MeshApiPigeonInternal.deepEquals(lhs.probeCount, rhs.probeCount) && MeshApiPigeonInternal.deepEquals(lhs.authenticated, rhs.authenticated) && MeshApiPigeonInternal.deepEquals(lhs.messageCount, rhs.messageCount) && MeshApiPigeonInternal.deepEquals(lhs.lastMessage, rhs.lastMessage) && MeshApiPigeonInternal.deepEquals(lhs.detail, rhs.detail)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BluetoothInfo")
    MeshApiPigeonInternal.deepHash(value: available, hasher: &hasher)
    MeshApiPigeonInternal.deepHash(value: authorized, hasher: &hasher)
    MeshApiPigeonInternal.deepHash(value: enabled, hasher: &hasher)
    MeshApiPigeonInternal.deepHash(value: active, hasher: &hasher)
    MeshApiPigeonInternal.deepHash(value: peerCount, hasher: &hasher)
    MeshApiPigeonInternal.deepHash(value: probeCount, hasher: &hasher)
    MeshApiPigeonInternal.deepHash(value: authenticated, hasher: &hasher)
    MeshApiPigeonInternal.deepHash(value: messageCount, hasher: &hasher)
    MeshApiPigeonInternal.deepHash(value: lastMessage, hasher: &hasher)
    MeshApiPigeonInternal.deepHash(value: detail, hasher: &hasher)
  }

  public var description: String {
    return "BluetoothInfo(available: \(String(describing: available)), authorized: \(String(describing: authorized)), enabled: \(String(describing: enabled)), active: \(String(describing: active)), peerCount: \(String(describing: peerCount)), probeCount: \(String(describing: probeCount)), authenticated: \(String(describing: authenticated)), messageCount: \(String(describing: messageCount)), lastMessage: \(String(describing: lastMessage)), detail: \(String(describing: detail)))"
  }
}

/// A native-certified message revealed only after durable verification and a
/// local receipt commit. The origin is the roster member from the signed
/// object, never a radio address or product-provided field.
///
/// Generated class from Pigeon that represents data sent in messages.
struct VerifiedIncomingText: Hashable, CustomStringConvertible {
  var authorId: String
  var objectId: String
  var verifiedAtUnixSeconds: Int64
  var body: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VerifiedIncomingText? {
    let authorId = pigeonVar_list[0] as! String
    let objectId = pigeonVar_list[1] as! String
    let verifiedAtUnixSeconds = pigeonVar_list[2] as! Int64
    let body = pigeonVar_list[3] as! String

    return VerifiedIncomingText(
      authorId: authorId,
      objectId: objectId,
      verifiedAtUnixSeconds: verifiedAtUnixSeconds,
      body: body
    )
  }
  func toList() -> [Any?] {
    return [
      authorId,
      objectId,
      verifiedAtUnixSeconds,
      body,
    ]
  }
  static func == (lhs: VerifiedIncomingText, rhs: VerifiedIncomingText) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MeshApiPigeonInternal.deepEquals(lhs.authorId, rhs.authorId) && MeshApiPigeonInternal.deepEquals(lhs.objectId, rhs.objectId) && MeshApiPigeonInternal.deepEquals(lhs.verifiedAtUnixSeconds, rhs.verifiedAtUnixSeconds) && MeshApiPigeonInternal.deepEquals(lhs.body, rhs.body)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("VerifiedIncomingText")
    MeshApiPigeonInternal.deepHash(value: authorId, hasher: &hasher)
    MeshApiPigeonInternal.deepHash(value: objectId, hasher: &hasher)
    MeshApiPigeonInternal.deepHash(value: verifiedAtUnixSeconds, hasher: &hasher)
    MeshApiPigeonInternal.deepHash(value: body, hasher: &hasher)
  }

  public var description: String {
    return "VerifiedIncomingText(authorId: \(String(describing: authorId)), objectId: \(String(describing: objectId)), verifiedAtUnixSeconds: \(String(describing: verifiedAtUnixSeconds)), body: \(String(describing: body)))"
  }
}

/// Native-certified durable voice. Metadata is revealed only after the
/// encrypted object and local receipt commit. Audio remains private to the
/// host and can be played only by its certified object ID.
///
/// Generated class from Pigeon that represents data sent in messages.
struct VerifiedIncomingVoice: Hashable, CustomStringConvertible {
  var authorId: String
  var objectId: String
  var logicalId: String
  var verifiedAtUnixSeconds: Int64
  var durationMillis: Int64
  var context: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VerifiedIncomingVoice? {
    let authorId = pigeonVar_list[0] as! String
    let objectId = pigeonVar_list[1] as! String
    let logicalId = pigeonVar_list[2] as! String
    let verifiedAtUnixSeconds = pigeonVar_list[3] as! Int64
    let durationMillis = pigeonVar_list[4] as! Int64
    let context = pigeonVar_list[5] as! String

    return VerifiedIncomingVoice(
      authorId: authorId,
      objectId: objectId,
      logicalId: logicalId,
      verifiedAtUnixSeconds: verifiedAtUnixSeconds,
      durationMillis: durationMillis,
      context: context
    )
  }
  func toList() -> [Any?] {
    return [
      authorId,
      objectId,
      logicalId,
      verifiedAtUnixSeconds,
      durationMillis,
      context,
    ]
  }
  static func == (lhs: VerifiedIncomingVoice, rhs: VerifiedIncomingVoice) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MeshApiPigeonInternal.deepEquals(lhs.authorId, rhs.authorId) && MeshApiPigeonInternal.deepEquals(lhs.objectId, rhs.objectId) && MeshApiPigeonInternal.deepEquals(lhs.logicalId, rhs.logicalId) && MeshApiPigeonInternal.deepEquals(lhs.verifiedAtUnixSeconds, rhs.verifiedAtUnixSeconds) && MeshApiPigeonInternal.deepEquals(lhs.durationMillis, rhs.durationMillis) && MeshApiPigeonInternal.deepEquals(lhs.context, rhs.context)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("VerifiedIncomingVoice")
    MeshApiPigeonInternal.deepHash(value: authorId, hasher: &hasher)
    MeshApiPigeonInternal.deepHash(value: objectId, hasher: &hasher)
    MeshApiPigeonInternal.deepHash(value: logicalId, hasher: &hasher)
    MeshApiPigeonInternal.deepHash(value: verifiedAtUnixSeconds, hasher: &hasher)
    MeshApiPigeonInternal.deepHash(value: durationMillis, hasher: &hasher)
    MeshApiPigeonInternal.deepHash(value: context, hasher: &hasher)
  }

  public var description: String {
    return "VerifiedIncomingVoice(authorId: \(String(describing: authorId)), objectId: \(String(describing: objectId)), logicalId: \(String(describing: logicalId)), verifiedAtUnixSeconds: \(String(describing: verifiedAtUnixSeconds)), durationMillis: \(String(describing: durationMillis)), context: \(String(describing: context)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct VoiceInfo: Hashable, CustomStringConvertible {
  var receivedCount: Int64
  var lastDurationMillis: Int64
  var ready: Bool
  var detail: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VoiceInfo? {
    let receivedCount = pigeonVar_list[0] as! Int64
    let lastDurationMillis = pigeonVar_list[1] as! Int64
    let ready = pigeonVar_list[2] as! Bool
    let detail = pigeonVar_list[3] as! String

    return VoiceInfo(
      receivedCount: receivedCount,
      lastDurationMillis: lastDurationMillis,
      ready: ready,
      detail: detail
    )
  }
  func toList() -> [Any?] {
    return [
      receivedCount,
      lastDurationMillis,
      ready,
      detail,
    ]
  }
  static func == (lhs: VoiceInfo, rhs: VoiceInfo) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MeshApiPigeonInternal.deepEquals(lhs.receivedCount, rhs.receivedCount) && MeshApiPigeonInternal.deepEquals(lhs.lastDurationMillis, rhs.lastDurationMillis) && MeshApiPigeonInternal.deepEquals(lhs.ready, rhs.ready) && MeshApiPigeonInternal.deepEquals(lhs.detail, rhs.detail)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("VoiceInfo")
    MeshApiPigeonInternal.deepHash(value: receivedCount, hasher: &hasher)
    MeshApiPigeonInternal.deepHash(value: lastDurationMillis, hasher: &hasher)
    MeshApiPigeonInternal.deepHash(value: ready, hasher: &hasher)
    MeshApiPigeonInternal.deepHash(value: detail, hasher: &hasher)
  }

  public var description: String {
    return "VoiceInfo(receivedCount: \(String(describing: receivedCount)), lastDurationMillis: \(String(describing: lastDurationMillis)), ready: \(String(describing: ready)), detail: \(String(describing: detail)))"
  }
}

/// Origin-local receipt evidence for one visible action. No object ID,
/// recipient identity, receipt or secret crosses into Flutter.
///
/// Generated class from Pigeon that represents data sent in messages.
struct DeliveryInfo: Hashable, CustomStringConvertible {
  var logicalId: String
  var targetCount: Int64
  var deliveredCount: Int64
  var state: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DeliveryInfo? {
    let logicalId = pigeonVar_list[0] as! String
    let targetCount = pigeonVar_list[1] as! Int64
    let deliveredCount = pigeonVar_list[2] as! Int64
    let state = pigeonVar_list[3] as! String

    return DeliveryInfo(
      logicalId: logicalId,
      targetCount: targetCount,
      deliveredCount: deliveredCount,
      state: state
    )
  }
  func toList() -> [Any?] {
    return [
      logicalId,
      targetCount,
      deliveredCount,
      state,
    ]
  }
  static func == (lhs: DeliveryInfo, rhs: DeliveryInfo) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MeshApiPigeonInternal.deepEquals(lhs.logicalId, rhs.logicalId) && MeshApiPigeonInternal.deepEquals(lhs.targetCount, rhs.targetCount) && MeshApiPigeonInternal.deepEquals(lhs.deliveredCount, rhs.deliveredCount) && MeshApiPigeonInternal.deepEquals(lhs.state, rhs.state)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("DeliveryInfo")
    MeshApiPigeonInternal.deepHash(value: logicalId, hasher: &hasher)
    MeshApiPigeonInternal.deepHash(value: targetCount, hasher: &hasher)
    MeshApiPigeonInternal.deepHash(value: deliveredCount, hasher: &hasher)
    MeshApiPigeonInternal.deepHash(value: state, hasher: &hasher)
  }

  public var description: String {
    return "DeliveryInfo(logicalId: \(String(describing: logicalId)), targetCount: \(String(describing: targetCount)), deliveredCount: \(String(describing: deliveredCount)), state: \(String(describing: state)))"
  }
}

/// Capability and discovery state for the direct Wi-Fi Aware radio.
/// It never exposes an IP address, SSID, router, or hotspot.
///
/// Generated class from Pigeon that represents data sent in messages.
struct AwareInfo: Hashable, CustomStringConvertible {
  var available: Bool
  var enabled: Bool
  var active: Bool
  var peerCount: Int64
  var maxPeers: Int64
  var state: String
  var detail: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AwareInfo? {
    let available = pigeonVar_list[0] as! Bool
    let enabled = pigeonVar_list[1] as! Bool
    let active = pigeonVar_list[2] as! Bool
    let peerCount = pigeonVar_list[3] as! Int64
    let maxPeers = pigeonVar_list[4] as! Int64
    let state = pigeonVar_list[5] as! String
    let detail = pigeonVar_list[6] as! String

    return AwareInfo(
      available: available,
      enabled: enabled,
      active: active,
      peerCount: peerCount,
      maxPeers: maxPeers,
      state: state,
      detail: detail
    )
  }
  func toList() -> [Any?] {
    return [
      available,
      enabled,
      active,
      peerCount,
      maxPeers,
      state,
      detail,
    ]
  }
  static func == (lhs: AwareInfo, rhs: AwareInfo) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MeshApiPigeonInternal.deepEquals(lhs.available, rhs.available) && MeshApiPigeonInternal.deepEquals(lhs.enabled, rhs.enabled) && MeshApiPigeonInternal.deepEquals(lhs.active, rhs.active) && MeshApiPigeonInternal.deepEquals(lhs.peerCount, rhs.peerCount) && MeshApiPigeonInternal.deepEquals(lhs.maxPeers, rhs.maxPeers) && MeshApiPigeonInternal.deepEquals(lhs.state, rhs.state) && MeshApiPigeonInternal.deepEquals(lhs.detail, rhs.detail)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AwareInfo")
    MeshApiPigeonInternal.deepHash(value: available, hasher: &hasher)
    MeshApiPigeonInternal.deepHash(value: enabled, hasher: &hasher)
    MeshApiPigeonInternal.deepHash(value: active, hasher: &hasher)
    MeshApiPigeonInternal.deepHash(value: peerCount, hasher: &hasher)
    MeshApiPigeonInternal.deepHash(value: maxPeers, hasher: &hasher)
    MeshApiPigeonInternal.deepHash(value: state, hasher: &hasher)
    MeshApiPigeonInternal.deepHash(value: detail, hasher: &hasher)
  }

  public var description: String {
    return "AwareInfo(available: \(String(describing: available)), enabled: \(String(describing: enabled)), active: \(String(describing: active)), peerCount: \(String(describing: peerCount)), maxPeers: \(String(describing: maxPeers)), state: \(String(describing: state)), detail: \(String(describing: detail)))"
  }
}

private class MeshApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return EngineInfo.fromList(self.readValue() as! [Any?])
    case 130:
      return DiagnosticEvent.fromList(self.readValue() as! [Any?])
    case 131:
      return EngineSnapshot.fromList(self.readValue() as! [Any?])
    case 132:
      return IdentityInfo.fromList(self.readValue() as! [Any?])
    case 133:
      return GroupInfo.fromList(self.readValue() as! [Any?])
    case 134:
      return CloudRelayProof.fromList(self.readValue() as! [Any?])
    case 135:
      return EnrollmentAccessPolicy.fromList(self.readValue() as! [Any?])
    case 136:
      return BluetoothInfo.fromList(self.readValue() as! [Any?])
    case 137:
      return VerifiedIncomingText.fromList(self.readValue() as! [Any?])
    case 138:
      return VerifiedIncomingVoice.fromList(self.readValue() as! [Any?])
    case 139:
      return VoiceInfo.fromList(self.readValue() as! [Any?])
    case 140:
      return DeliveryInfo.fromList(self.readValue() as! [Any?])
    case 141:
      return AwareInfo.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MeshApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? EngineInfo {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? DiagnosticEvent {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? EngineSnapshot {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? IdentityInfo {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? GroupInfo {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? CloudRelayProof {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? EnrollmentAccessPolicy {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? BluetoothInfo {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? VerifiedIncomingText {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? VerifiedIncomingVoice {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? VoiceInfo {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? DeliveryInfo {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? AwareInfo {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MeshApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MeshApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MeshApiPigeonCodecWriter(data: data)
  }
}

class MeshApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MeshApiPigeonCodec(readerWriter: MeshApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol MeshHostApi {
  func engineInfo() async throws -> EngineInfo
  func prepareIdentity() async throws -> IdentityInfo
  func groupInfo() async throws -> GroupInfo
  func createGroup() async throws -> GroupInfo
  func exportInvitation() async throws -> FlutterStandardTypedData
  func createEnrollmentRequest(invitation: FlutterStandardTypedData) async throws -> FlutterStandardTypedData
  func issueEnrollment(request: FlutterStandardTypedData) async throws -> FlutterStandardTypedData
  /// Reports whether this identity is the authority certified in the current
  /// group policy. It never exposes authority keys or membership material.
  func canIssueEnrollment() async throws -> Bool
  func signCloudRelay(canonical: FlutterStandardTypedData) async throws -> CloudRelayProof
  /// The current authority signs a short-lived public handoff to an existing
  /// certified member. The host does not reveal its private authority key.
  func prepareAuthorityHandoff(successor: FlutterStandardTypedData, validUntil: Int64) async throws -> FlutterStandardTypedData
  /// The promoted member creates the next policy on its own protected store.
  func rotateAuthority(handoff: FlutterStandardTypedData) async throws -> FlutterStandardTypedData
  /// Existing members accept an authority replacement only with the matching
  /// old-authority handoff.
  func installRotatedPolicy(policy: FlutterStandardTypedData, handoff: FlutterStandardTypedData) async throws -> GroupInfo
  func installPolicy(policy: FlutterStandardTypedData) async throws -> GroupInfo
  func configureEnrollmentAccess(policy: EnrollmentAccessPolicy) async throws
  func clearEnrollmentAccess() async throws
  func bluetoothInfo() async throws -> BluetoothInfo
  func prepareBluetooth() async throws -> BluetoothInfo
  func startBluetoothDiscovery() async throws -> BluetoothInfo
  func stopBluetoothDiscovery() async throws -> BluetoothInfo
  func awareInfo() async throws -> AwareInfo
  func startAwareDiscovery() async throws -> AwareInfo
  func stopAwareDiscovery() async throws -> AwareInfo
  func sendText(message: String, logicalId: String) async throws -> Bool
  func deliveryInfo(logicalId: String) async throws -> DeliveryInfo
  func drainVerifiedIncomingText() async throws -> [VerifiedIncomingText]
  func drainVerifiedIncomingVoice() async throws -> [VerifiedIncomingVoice]
  func voiceInfo() async throws -> VoiceInfo
  func sendVoice(audio: FlutterStandardTypedData, durationMillis: Int64, logicalId: String) async throws -> Bool
  func sendVoiceWithContext(audio: FlutterStandardTypedData, durationMillis: Int64, logicalId: String, context: String) async throws -> Bool
  func playLastVoice() async throws -> Bool
  func playVoice(objectId: String) async throws -> Bool
  func subscribe(cursor: Int64) async throws -> EngineSnapshot
  func verifyBridge(requestId: Int64) async throws -> EngineSnapshot
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class MeshHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MeshApiPigeonCodec.shared }
  /// Sets up an instance of `MeshHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: MeshHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let engineInfoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mesh_host.MeshHostApi.engineInfo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      engineInfoChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.engineInfo()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      engineInfoChannel.setMessageHandler(nil)
    }
    let prepareIdentityChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mesh_host.MeshHostApi.prepareIdentity\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      prepareIdentityChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.prepareIdentity()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      prepareIdentityChannel.setMessageHandler(nil)
    }
    let groupInfoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mesh_host.MeshHostApi.groupInfo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      groupInfoChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.groupInfo()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      groupInfoChannel.setMessageHandler(nil)
    }
    let createGroupChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mesh_host.MeshHostApi.createGroup\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createGroupChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.createGroup()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      createGroupChannel.setMessageHandler(nil)
    }
    let exportInvitationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mesh_host.MeshHostApi.exportInvitation\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      exportInvitationChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.exportInvitation()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      exportInvitationChannel.setMessageHandler(nil)
    }
    let createEnrollmentRequestChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mesh_host.MeshHostApi.createEnrollmentRequest\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createEnrollmentRequestChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let invitationArg = args[0] as! FlutterStandardTypedData
        Task { @MainActor in
          do {
            let result = try await api.createEnrollmentRequest(invitation: invitationArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      createEnrollmentRequestChannel.setMessageHandler(nil)
    }
    let issueEnrollmentChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mesh_host.MeshHostApi.issueEnrollment\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      issueEnrollmentChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! FlutterStandardTypedData
        Task { @MainActor in
          do {
            let result = try await api.issueEnrollment(request: requestArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      issueEnrollmentChannel.setMessageHandler(nil)
    }
    /// Reports whether this identity is the authority certified in the current
    /// group policy. It never exposes authority keys or membership material.
    let canIssueEnrollmentChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mesh_host.MeshHostApi.canIssueEnrollment\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      canIssueEnrollmentChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.canIssueEnrollment()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      canIssueEnrollmentChannel.setMessageHandler(nil)
    }
    let signCloudRelayChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mesh_host.MeshHostApi.signCloudRelay\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      signCloudRelayChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let canonicalArg = args[0] as! FlutterStandardTypedData
        Task { @MainActor in
          do {
            let result = try await api.signCloudRelay(canonical: canonicalArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      signCloudRelayChannel.setMessageHandler(nil)
    }
    /// The current authority signs a short-lived public handoff to an existing
    /// certified member. The host does not reveal its private authority key.
    let prepareAuthorityHandoffChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mesh_host.MeshHostApi.prepareAuthorityHandoff\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      prepareAuthorityHandoffChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let successorArg = args[0] as! FlutterStandardTypedData
        let validUntilArg = args[1] as! Int64
        Task { @MainActor in
          do {
            let result = try await api.prepareAuthorityHandoff(successor: successorArg, validUntil: validUntilArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      prepareAuthorityHandoffChannel.setMessageHandler(nil)
    }
    /// The promoted member creates the next policy on its own protected store.
    let rotateAuthorityChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mesh_host.MeshHostApi.rotateAuthority\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rotateAuthorityChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let handoffArg = args[0] as! FlutterStandardTypedData
        Task { @MainActor in
          do {
            let result = try await api.rotateAuthority(handoff: handoffArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      rotateAuthorityChannel.setMessageHandler(nil)
    }
    /// Existing members accept an authority replacement only with the matching
    /// old-authority handoff.
    let installRotatedPolicyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mesh_host.MeshHostApi.installRotatedPolicy\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      installRotatedPolicyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let policyArg = args[0] as! FlutterStandardTypedData
        let handoffArg = args[1] as! FlutterStandardTypedData
        Task { @MainActor in
          do {
            let result = try await api.installRotatedPolicy(policy: policyArg, handoff: handoffArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      installRotatedPolicyChannel.setMessageHandler(nil)
    }
    let installPolicyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mesh_host.MeshHostApi.installPolicy\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      installPolicyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let policyArg = args[0] as! FlutterStandardTypedData
        Task { @MainActor in
          do {
            let result = try await api.installPolicy(policy: policyArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      installPolicyChannel.setMessageHandler(nil)
    }
    let configureEnrollmentAccessChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mesh_host.MeshHostApi.configureEnrollmentAccess\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      configureEnrollmentAccessChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let policyArg = args[0] as! EnrollmentAccessPolicy
        Task { @MainActor in
          do {
            try await api.configureEnrollmentAccess(policy: policyArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      configureEnrollmentAccessChannel.setMessageHandler(nil)
    }
    let clearEnrollmentAccessChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mesh_host.MeshHostApi.clearEnrollmentAccess\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearEnrollmentAccessChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            try await api.clearEnrollmentAccess()
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      clearEnrollmentAccessChannel.setMessageHandler(nil)
    }
    let bluetoothInfoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mesh_host.MeshHostApi.bluetoothInfo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      bluetoothInfoChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.bluetoothInfo()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      bluetoothInfoChannel.setMessageHandler(nil)
    }
    let prepareBluetoothChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mesh_host.MeshHostApi.prepareBluetooth\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      prepareBluetoothChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.prepareBluetooth()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      prepareBluetoothChannel.setMessageHandler(nil)
    }
    let startBluetoothDiscoveryChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mesh_host.MeshHostApi.startBluetoothDiscovery\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startBluetoothDiscoveryChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.startBluetoothDiscovery()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      startBluetoothDiscoveryChannel.setMessageHandler(nil)
    }
    let stopBluetoothDiscoveryChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mesh_host.MeshHostApi.stopBluetoothDiscovery\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopBluetoothDiscoveryChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.stopBluetoothDiscovery()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      stopBluetoothDiscoveryChannel.setMessageHandler(nil)
    }
    let awareInfoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mesh_host.MeshHostApi.awareInfo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      awareInfoChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.awareInfo()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      awareInfoChannel.setMessageHandler(nil)
    }
    let startAwareDiscoveryChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mesh_host.MeshHostApi.startAwareDiscovery\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startAwareDiscoveryChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.startAwareDiscovery()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      startAwareDiscoveryChannel.setMessageHandler(nil)
    }
    let stopAwareDiscoveryChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mesh_host.MeshHostApi.stopAwareDiscovery\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopAwareDiscoveryChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.stopAwareDiscovery()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      stopAwareDiscoveryChannel.setMessageHandler(nil)
    }
    let sendTextChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mesh_host.MeshHostApi.sendText\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendTextChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let messageArg = args[0] as! String
        let logicalIdArg = args[1] as! String
        Task { @MainActor in
          do {
            let result = try await api.sendText(message: messageArg, logicalId: logicalIdArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      sendTextChannel.setMessageHandler(nil)
    }
    let deliveryInfoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mesh_host.MeshHostApi.deliveryInfo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      deliveryInfoChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let logicalIdArg = args[0] as! String
        Task { @MainActor in
          do {
            let result = try await api.deliveryInfo(logicalId: logicalIdArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      deliveryInfoChannel.setMessageHandler(nil)
    }
    let drainVerifiedIncomingTextChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mesh_host.MeshHostApi.drainVerifiedIncomingText\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      drainVerifiedIncomingTextChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.drainVerifiedIncomingText()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      drainVerifiedIncomingTextChannel.setMessageHandler(nil)
    }
    let drainVerifiedIncomingVoiceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mesh_host.MeshHostApi.drainVerifiedIncomingVoice\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      drainVerifiedIncomingVoiceChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.drainVerifiedIncomingVoice()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      drainVerifiedIncomingVoiceChannel.setMessageHandler(nil)
    }
    let voiceInfoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mesh_host.MeshHostApi.voiceInfo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      voiceInfoChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.voiceInfo()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      voiceInfoChannel.setMessageHandler(nil)
    }
    let sendVoiceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mesh_host.MeshHostApi.sendVoice\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendVoiceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let audioArg = args[0] as! FlutterStandardTypedData
        let durationMillisArg = args[1] as! Int64
        let logicalIdArg = args[2] as! String
        Task { @MainActor in
          do {
            let result = try await api.sendVoice(audio: audioArg, durationMillis: durationMillisArg, logicalId: logicalIdArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      sendVoiceChannel.setMessageHandler(nil)
    }
    let sendVoiceWithContextChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mesh_host.MeshHostApi.sendVoiceWithContext\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendVoiceWithContextChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let audioArg = args[0] as! FlutterStandardTypedData
        let durationMillisArg = args[1] as! Int64
        let logicalIdArg = args[2] as! String
        let contextArg = args[3] as! String
        Task { @MainActor in
          do {
            let result = try await api.sendVoiceWithContext(audio: audioArg, durationMillis: durationMillisArg, logicalId: logicalIdArg, context: contextArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      sendVoiceWithContextChannel.setMessageHandler(nil)
    }
    let playLastVoiceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mesh_host.MeshHostApi.playLastVoice\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      playLastVoiceChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.playLastVoice()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      playLastVoiceChannel.setMessageHandler(nil)
    }
    let playVoiceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mesh_host.MeshHostApi.playVoice\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      playVoiceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let objectIdArg = args[0] as! String
        Task { @MainActor in
          do {
            let result = try await api.playVoice(objectId: objectIdArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      playVoiceChannel.setMessageHandler(nil)
    }
    let subscribeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mesh_host.MeshHostApi.subscribe\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      subscribeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let cursorArg = args[0] as! Int64
        Task { @MainActor in
          do {
            let result = try await api.subscribe(cursor: cursorArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      subscribeChannel.setMessageHandler(nil)
    }
    let verifyBridgeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mesh_host.MeshHostApi.verifyBridge\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      verifyBridgeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestIdArg = args[0] as! Int64
        Task { @MainActor in
          do {
            let result = try await api.verifyBridge(requestId: requestIdArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      verifyBridgeChannel.setMessageHandler(nil)
    }
  }
}
